### ISSUE TITLE
I encountered difficulties when downloading the data

### ISSUE THREAD

**Issue by heyuanpengpku** [Yebulabula/OpenDlign#2]
Great and very interesting work! However, I encountered difficulties when downloading the data used in this paper. 
The download would either timeout or there would be errors indicating that the actual file size does not match the expected size. Could you please upload the data to Google Drive or Baidu Netdisk for download? 
I greatly appreciate your help!

**Comment by Yebulabula** [comment]
Hi @heyuanpengpku,

Many thanks for your interest in our work. It seems like the timeout issue might be caused by a firewall, and using a VPN could help resolve it. I just tested in on my computer, I could download it without any errors. I apologize that I'm unable to upload all the data to the cloud drive due to its large size (over 300GB in total).

Best wishes,  
Ye Mao
